import type { Metadata } from "next";
import { Inter, VT323 } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

const inter = VT323({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Dev Snack - A Developers Newsletter",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NextTopLoader showSpinner={false} color="#18d619" />
				{children}
			</body>
		</html>
	);
}
